### PR TITLE
Create Anagram Substring Search Given a string A and a string B.  Fin…

### PR DESCRIPTION
**Pull request by sayantann11**
…d and return the starting indices of the substrings of A which matches any of the anagrams of B.  Note: An anagram is a play on words created by rearranging the letters of the original word to make a new word or phrase   Input Format  The arguments given are string A and string B. Output Format  Return the starting indices of the substrings of A which matches any of the anagrams of B. Constraints  1 <= length of the string A,B <= 100000 length of string A > length of string B 'a' < = A[i] ,B[i] < ='z' For Example  Input 1:     A = "BACDGABCDA"     B = "ABCD" Output 1:     [0, 5, 6]  Input 2:     A = "AAABABAA"     B = "AABA" Output 2:     [0, 1, 4]

### CODE REVIEW

**Review by sunilkumarmaurya786693 — COMMENTED** [review]
Can u add question link? It will more beneficial for other who practice it. 
Also if u like my hard work, give star on this reposatory.

**Review by sunilkumarmaurya786693 — APPROVED** [review]
code review done and code look fine

**Comment by sayantann11** [comment]
I liked your work so much thanks for approving it I am new to this I will
try to edit and provide the link too..

**Comment by sayantann11** [comment]
yes
https://www.scaler.com/academy/mentee-dashboard/classroom/working-with-functions-ea18c417-64b6-4f2a-973e-5ace86345470/#homework%2F9271

**Pull request merged**
